name: Deb Canary

on:
  # This workflow will run from the release-automation.yaml automation on each merge
  workflow_dispatch:
    inputs:
      ref_name:
        required: true
        type: string
  workflow_call:
    inputs:
      ref_name:
        required: true
        type: string

  # This workflow will run every 5 min
  schedule:
    - cron: '*/5 * * * *'
  
  # This workflow will run when the workflow file is updated
  pull_request:
    paths:
      - '.github/workflows/canary-deb.yaml'
  
jobs:
  get-latest-tag:
    name: Get the latest release tag
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      tag: ${{ steps.latest-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: 'Get the latest tag'
        id: latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@04e8485ecb6487243907e330d522ff60f02283ce" # v1.4.0

  canary-deb:
    name: Test Finch APT repo health
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: get-latest-tag
    steps:
      - name: Add Finch APT Repository
        run: |
          ARCH=$(dpkg --print-architecture)
          echo "ARCH=${ARCH}" >> $GITHUB_ENV
          echo "Detected architecture: $ARCH"

          echo "filename=$(runfinch-finch_${{ needs.get-latest-tag.outputs.tag }}_${{ env.ARCH }}.deb)" >> $GITHUB_ENV
          
          curl -fsSL https://artifact.runfinch.com/deb/GPG_KEY.pub | sudo gpg --dearmor -o /usr/share/keyrings/runfinch-finch-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/runfinch-finch-archive-keyring.gpg arch=$ARCH] https://artifact.runfinch.com/deb noble main" | sudo tee /etc/apt/sources.list.d/runfinch-finch.list
          sudo apt update

      - name: Download latest release from GitHub
        uses: robinraju/release-downloader@https://github.com/robinraju/release-downloader/commit/daf26c55d821e836577a15f77d86ddc078948b05 # v1.12.0
        with:
          tag: ${{ needs.get-latest-tag.outputs.tag }}
          fileName: ${{ env.filename }}
          out-file-path: github-release

      - name: Install Finch with APT
        run: sudo apt install runfinch-finch -y --download-only
        
      - name: Verify version matches latest release
        run: |
          apt_file=/var/cache/apt/archives/${{ env.filename }}
          apt_file_shasum=$(sha256sum ${apt_file})
          github_file=${GITHUB_WORKSPACE}/github-release/${{ env.filename }}
          github_file_shasum=$(sha256sum ${github_file}))
          
          if [[ $(diff <(echo ${apt_file_shasum}) <(echo ${github_file_shasum}) ]]; then
            echo "❌ sha256sum mismatch!"
            echo "apt repo shasum: ${apt_file_shasum}"
            echo "GitHub release shasum: ${github_file_shasum}"
            exit 1
          else
            echo "✅ shasum ${apt_file_shasum} identical"
          fi
      - name: Clean up environment
        run: rm /var/cache/apt/archives/${{ env.filename }}
